[build]
  publish = "."
  functions = "netlify/functions"

# Optional: redirects API requests to the function
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
